Migrate to Yara-X
vipyrsec/dragonfly-client-rs pull request #123
Opened 2024-07-11 02:40 UTC by Robin5605

Closes #122

2024-07-14 19:23 UTC, Robin5605 commented
todo: CI

2024-07-14 19:46 UTC, sid-maddy commented
> todo: CI

https://github.com/vipyrsec/dragonfly-client-rs/pull/127

2024-07-27 00:33 UTC, jonathan-d-zhang requested changes
lgtm except a few comments

2024-07-27 00:33 UTC, jonathan-d-zhang commented on src/client/models.rs
> +        compiler.add_source(rules_str.as_str())?;
Can't we skip this joining together and just
```rs
for rule_def in self.rules.values() {
    compiler.add_source(rule_def.as_str())?;
}
```

2024-07-27 00:33 UTC, jonathan-d-zhang commented on src/scanner.rs
> +fn scan_file(file: &mut impl Read, path: &Path, rules: &yara_x::Rules) -> Result<FileScanResult> {
nit
```suggestion
fn scan_file(file: &mut impl Read, path: &Path, rules: &Rules) -> Result<FileScanResult> {
```

2024-07-27 02:23 UTC, jonathan-d-zhang approved these changes
:shipit:

2024-07-27 02:23 UTC, merged